<a href="https://colab.research.google.com/github/ADML003/Tensorflow/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#FUNDAMENTALS OF TENSORS USING TENSORFLOW




## Introduction to Tensors


In [96]:
# import tensorflow

import tensorflow as tf
print(tf.__version__)



2.17.0


In [97]:
# first tensor creation with tf.constant()

scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [98]:
# check the numbers of dimension of a number
scalar.ndim

0

In [99]:
# creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [100]:
vector.ndim

1

In [101]:
# creating a matrix with more than one dimension

matric=tf.constant([[10,8],[34,22]])

matric

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [34, 22]], dtype=int32)>

In [102]:
matric.ndim

2

In [103]:
# new matrix

another_matrix=tf.constant([[10.,5.],
                            [3.,4.],
                            [6.,8.]], dtype=tf.float16) #specify the data type
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 3.,  4.],
       [ 6.,  8.]], dtype=float16)>

In [104]:
another_matrix.ndim

2

In [105]:
# lets create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [106]:
tensor.ndim

3

#####using tf.variable for tensor creation



what we have done so far:

- scalar: a single number
- vector: a number with a directional_link
- matrix: a 2 dimensional array of number
- tensor: an n-dimensional array of numbers ( 0 dimensional tensor is called a  scalar and a  1 dimensional tensor is called a vector)

In [107]:
#using tf.Variable()  for tensor creation

mu_tensor= tf.Variable([19,8])
mun_tensor= tf.constant([19,8])
mu_tensor, mun_tensor # changable tensor and then unchangable tensor



(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([19,  8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([19,  8], dtype=int32)>)

In [109]:
# changing elements in chanagable tensor

mu_tensor[0]= 7
mu_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [110]:
# trying .assign()

mu_tensor[0].assign(7)
mu_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 8], dtype=int32)>

In [111]:

mun_tensor[0].assign(4)
mun_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

#creating random tensors

###random tensors are the tensors of some arbitrary size which contain random number

In [ ]:
# create two random tesors

random_1= tf.random.Generator.from_seed(7)# setting the seed is jsut for the reproducibility
random_1= random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(7)
random_2=random_2.normal(shape=(3,2))

#Are they equal??

random_1, random_2, random_1==random_2

In [ ]:
#shuffle a tensor(valuable when we want to shuffle the data)

not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])

#shuffle our non_shuffled tensor

tf.random.shuffle(not_shuffled)

In [ ]:
#shuffle a tensor(valuable when we want to shuffle the data)

not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])

#shuffle our non_shuffled tensor

tf.random.shuffle(not_shuffled,seed=42)

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

##other ways to make tensors

In [ ]:
tf.ones([10,7])

In [ ]:
tf.zeros(shape=(3,4))

### working with numpy and converting numpy into tensors

In [ ]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)

In [ ]:
numpy_A

In [ ]:
A= tf.constant(numpy_A)

In [ ]:
A

In [ ]:
B= tf.constant(numpy_A, shape=(2,3,4)) # remember the shape product should be equal to the number of elements in the numpy array NOT LESSER NOT GREATER!!
B

In [ ]:
A.ndim

In [ ]:
B.ndim

#Getting information from the Tensors


- Shape. using tensor.shape ( number of elements in each dimension) **
- Rank   using tensor.ndim (no.of tensor dimensions)
- Axis of dimension  tensor[0] (particular dimension of a tensor)
- size tf.size(tensor)( total number of items in the tensor)



In [ ]:
A.shape
A.ndim
A[2]
tf.size(A)

In [ ]:
A.ndim

In [ ]:
A[2]


In [ ]:
tf.size(A)

In [ ]:
tf.size(B)

In [ ]:
B.shape

In [ ]:
B.ndim

In [112]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [113]:
## creaitng a rank 4 tensor

rank_4_tensor = tf.zeros(shape=(2,3,2,4))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 2, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

the product of the shape elements together will give the total number of elements i.e. the size of the tensor.


In [114]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 2, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

In [115]:
2*3*2*4

48

👆 the total size of the tensor

In [116]:
rank_4_tensor.shape[3]

4

In [117]:
rank_4_tensor.shape[-1] #last axis elements

4

In [118]:
tf.size(rank_4_tensor).numpy()

48

### Indexing Tensors

In [119]:
# get first two elements of each tensor

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [120]:
# get the first element of each dimension from each index except for the final one

rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [121]:
# creating a rank 2 tensor

rank2=tf.constant([[10,7],[3,4]])
rank2.shape, rank2.ndim

(TensorShape([2, 2]), 2)

In [122]:
# getting the last item of each row of the rank 2 tensor

rank2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [123]:
# adding an extra dimension to rank 2 tensor

rank3=rank2[...,tf.newaxis]
rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [124]:
#alternative to newaxis

tf.expand_dims(rank2,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

#Manipulating tensors

## Tensor Operations

In [125]:
#  using default python operaotors we can easily add values
tensor= tf.constant([[10,7],[34,44]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [44, 54]], dtype=int32)>

In [126]:
tensor #original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [34, 44]], dtype=int32)>

##Matrix multiplication

most common tensor operaitons

using tf.linalg.matmul fucntion however the intermediary linalg here is droppable here.


## Rules of matrix multiplication
- the inner dimensions must match
- the resulting matrix will be of the order of the inner dimensions

In [127]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [34, 44]], dtype=int32)>

In [128]:
print(tensor)

tf.Tensor(
[[10  7]
 [34 44]], shape=(2, 2), dtype=int32)


In [129]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 338,  378],
       [1836, 2174]], dtype=int32)>

In [130]:
tensor@tensor  # @ operator is used for matrix multiplication in pyhton

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 338,  378],
       [1836, 2174]], dtype=int32)>

In [131]:
# creating a 3,2 tensor

tensor32=tf.constant([[1,2],[3,4],[5,6]])

# another 3,2 tensor

tensor32_=tf.constant([[7,8],[9,10],[11,12]])

tensor32,tensor32_

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [132]:
tensor32[..., tf.newaxis]
tensor32

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [133]:
t=tensor32[...,tf.newaxis]
t.shape

TensorShape([3, 2, 1])

In [134]:
t.ndim

3

In [135]:
# lets change the shape of tensor32

# the original tensor remains the same as it was declared as tf.constant while creating

new_tensor=tf.reshape(tensor32,shape=(2,3)) # have to store it in a separate  variable

new_tensor.shape, tensor32_.shape



(TensorShape([2, 3]), TensorShape([3, 2]))

In [136]:
tf.matmul(new_tensor,tensor32_)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [137]:
## now changing the shape of the other matrix

tf.matmul(tensor32,tf.reshape(tensor32_,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [138]:
tf.transpose(tensor32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [139]:
print(tensor32)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [140]:
# trying matrix multiplication with matrix transpose rather than reshaping

tf.matmul(tf.transpose(tensor32), tensor32_)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [141]:
tensor32.shape, tensor32_.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

Generallly when performing matrix multiplication two matrices and the required condition is not met then , use tf.transpose() function for effective multiplication.



#Changing the datatype of a tensor

In [142]:
f=tf.constant([[2.3,3.2],[3.2,2.2]])
f.dtype

tf.float32

In [143]:
i=tf.constant([[3,4],[2,2]])
i.dtype

tf.int32

In [144]:
tf.__version__

'2.17.0'

In [145]:
# Change from float32 to float16

g=tf.cast(i,dtype=tf.float16)
g, g.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[3., 4.],
        [2., 2.]], dtype=float16)>,
 tf.float16)

## Aggregating tensors

condensing them from multiple values down to a smaller amount of values.

In [146]:
# getting the absolute values

D= tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [147]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Lets go through the following forms of aggregation:
- Get the minimum
- Get the maximum
- Get the mean of a tensor
- Get the sum of a tensor

In [148]:
# creating random tensor with values between 0 and 100 of size 50
E= tf.constant(np.random.randint(0,100,size=50))
E



<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([74, 78, 19, 91,  3, 22, 54, 42, 72, 42, 21, 28, 77, 72, 54, 49, 60,
       82, 71, 68, 68, 55, 14, 35, 87, 33, 37, 82, 74, 60,  2, 67,  8, 44,
       69, 82,  0, 33, 50, 76, 88, 59, 10, 96, 63, 96, 10, 66, 64, 59])>

In [149]:
tf.size(E).numpy(), E.shape, E.ndim

(50, TensorShape([50]), 1)

In [150]:
# find the minimum of a tensor

tf.reduce_min(E).numpy()

0

In [151]:
# find the maximum of a tensor

tf.reduce_max(E).numpy()

96

In [152]:
# find the mean

tf.reduce_mean(E).numpy()

53

In [153]:
# finding the sum of the tensor
tf.reduce_sum(E).numpy()

2666

In [154]:
# finding the variance of our tensor

#!!!!no reduce method for tfp

import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=716>

In [155]:
# finding the standard variation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32)) # having to change the  dtype when type error comes in


<tf.Tensor: shape=(), dtype=float32, numpy=26.763737>

In [156]:
# find the variance of our E tensor


# ALTERNATE TO TENSOFLOW_PROBABILITY APPROACH
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=716.2976>

In [166]:
# positional maximum and minimum
tf.random.set_seed(43)
F= tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
       0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
       0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
       0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
       0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
       0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
       0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
       0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
       0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
       0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ],
      dtype=float32)>

In [167]:
# find the positional maximum

In [168]:

tf.argmax(F) # returns the index with the maximum value

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [169]:
# index on our largest value position

F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

In [170]:
# find the max value of F

tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

In [171]:
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [172]:
#find the positional minimum

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [173]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0015381575>

## Squeezing a tensor (removing all single dimensions)



In [174]:
tf.random.set_seed(42)

G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50
                                                   ))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [175]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [177]:
G_squee=tf.squeeze(G)
G_squee,G_squee.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# one-hot encoding in tensors

 a form of numerical encoding

In [178]:
# create a list of indices

some_list=[0,1,2,3]

# one hot encode our list of indices

tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Squaring, log, square root

In [180]:
H=tf.range(1,10)
H


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [181]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [183]:
tf.sqrt(tf.cast(H,dtype=tf.float32))#method requires non int type of inputs

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [185]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#Tensor and Numpy
Tensorflow interacts well with the numpy arrays.

In [186]:
#create a tensor direclty from a Numpy array

J=tf.constant(np.array([3.,4.,5.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 5.])>

In [187]:
np.array(J),type(np.array(J))

(array([3., 4., 5.]), numpy.ndarray)

In [188]:
type(J)

tensorflow.python.framework.ops.EagerTensor

In [189]:
# convert tensor J to a Numpy array

J.numpy(), type(J.numpy())

(array([3., 4., 5.]), numpy.ndarray)

In [193]:
J=tf.constant([3.])
J.numpy()[0]

3.0

In [194]:
J.dtype

tf.float32

In [196]:
N=tf.constant(np.array([3.,2.,4.])) # its data type is always gonna be float64
N.dtype

tf.float64