<a href="https://colab.research.google.com/github/ADML003/Tensorflow/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#FUNDAMENTALS OF TENSORS USING TENSORFLOW




## Introduction to Tensors


In [3]:
# import tensorflow

import tensorflow as tf
print(tf.__version__)



2.17.0


In [4]:
# first tensor creation with tf.constant()

scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check the numbers of dimension of a number
scalar.ndim

0

In [6]:
# creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# creating a matrix with more than one dimension

matric=tf.constant([[10,8],[34,22]])

matric

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [34, 22]], dtype=int32)>

In [9]:
matric.ndim

2

In [10]:
# new matrix

another_matrix=tf.constant([[10.,5.],
                            [3.,4.],
                            [6.,8.]], dtype=tf.float16) #specify the data type
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 3.,  4.],
       [ 6.,  8.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
# lets create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

#####using tf.variable for tensor creation



what we have done so far:

- scalar: a single number
- vector: a number with a directional_link
- matrix: a 2 dimensional array of number
- tensor: an n-dimensional array of numbers ( 0 dimensional tensor is called a  scalar and a  1 dimensional tensor is called a vector)

In [18]:
#using tf.Variable()  for tensor creation

mu_tensor= tf.Variable([19,8])
mun_tensor= tf.constant([19,8])
mu_tensor, mun_tensor # changable tensor and then unchangable tensor



(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([19,  8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([19,  8], dtype=int32)>)

In [19]:
# changing elements in chanagable tensor

mu_tensor[0]= 7
mu_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [20]:
# trying .assign()

mu_tensor[0].assign(7)
mu_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 8], dtype=int32)>

In [29]:

mun_tensor[0].assign(4)
mun_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

#creating random tensors

###random tensors are the tensors of some arbitrary size which contain random number

In [38]:
# create two random tesors

random_1= tf.random.Generator.from_seed(7)# setting the seed is jsut for the reproducibility
random_1= random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(7)
random_2=random_2.normal(shape=(3,2))

#Are they equal??

random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [45]:
#shuffle a tensor(valuable when we want to shuffle the data)

not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])

#shuffle our non_shuffled tensor

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [46]:
#shuffle a tensor(valuable when we want to shuffle the data)

not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])

#shuffle our non_shuffled tensor

tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [47]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

##other ways to make tensors

In [48]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [58]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### working with numpy and converting numpy into tensors

In [59]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)

In [60]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [61]:
A= tf.constant(numpy_A)

In [62]:
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [69]:
B= tf.constant(numpy_A, shape=(2,3,4)) # remember the shape product should be equal to the number of elements in the numpy array NOT LESSER NOT GREATER!!
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [70]:
A.ndim

1

In [71]:
B.ndim

3

#Getting information from the Tensors


- Shape. using tensor.shape ( number of elements in each dimension) **
- Rank   using tensor.ndim (no.of tensor dimensions)
- Axis of dimension  tensor[0] (particular dimension of a tensor)
- size tf.size(tensor)( total number of items in the tensor)



In [73]:
A.shape
A.ndim
A[2]
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [74]:
A.ndim

1

In [75]:
A[2]


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [76]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [77]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [78]:
B.shape

TensorShape([2, 3, 4])

In [79]:
B.ndim

3

In [80]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [83]:
## creaitng a rank 4 tensor

rank_4_tensor = tf.zeros(shape=(2,3,2,4))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 2, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

the product of the shape elements together will give the total number of elements i.e. the size of the tensor.


In [84]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 2, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

In [85]:
2*3*2*4

48

👆 the total size of the tensor

In [88]:
rank_4_tensor.shape[3]

4

In [91]:
rank_4_tensor.shape[-1] #last axis elements

4

In [92]:
tf.size(rank_4_tensor).numpy()

48